export const PLANS = {
  FREE: {
    name: "Free",
    price: 0,
    socialAccounts: 1,
    aiGenerationsPerMonth: 10,
    scheduling: false,
    analytics: false,
    brandVoiceRag: false,
    teamSeats: 1,
    brandAssets: 5,
    customTemplates: 3,
    videoGeneration: false,
    maxOrganizations: 1,
  },
  STARTER: {
    name: "Starter",
    price: 2900,
    priceAnnual: 24167,
    socialAccounts: 5,
    aiGenerationsPerMonth: 200,
    scheduling: true,
    analytics: true,
    brandVoiceRag: false,
    teamSeats: 1,
    brandAssets: 50,
    customTemplates: 20,
    videoGeneration: true,
    maxOrganizations: 1,
  },
  PRO: {
    name: "Pro",
    price: 3900,
    priceAnnual: 32500,
    socialAccounts: 15,
    aiGenerationsPerMonth: -1,
    scheduling: true,
    analytics: true,
    brandVoiceRag: true,
    teamSeats: 1,
    brandAssets: -1,
    customTemplates: -1,
    videoGeneration: true,
    maxOrganizations: 1,
  },
  TEAM: {
    name: "Team",
    price: 7900,
    priceAnnual: 65833,
    socialAccounts: 15,
    aiGenerationsPerMonth: -1,
    scheduling: true,
    analytics: true,
    brandVoiceRag: true,
    teamSeats: 5,
    brandAssets: -1,
    customTemplates: -1,
    videoGeneration: true,
    maxOrganizations: 1,
  },
  AGENCY: {
    name: "Agency",
    price: 14900,
    priceAnnual: 124167,
    socialAccounts: 25,
    aiGenerationsPerMonth: -1,
    scheduling: true,
    analytics: true,
    brandVoiceRag: true,
    teamSeats: 3,
    brandAssets: -1,
    customTemplates: -1,
    videoGeneration: true,
    maxOrganizations: 10,
  },
} as const

export type PlanKey = keyof typeof PLANS
