export const SOCIAL_OAUTH_CONFIG = {
  INSTAGRAM: {
    name: "Instagram",
    icon: "Instagram",
    color: "text-pink-500",
    bgColor: "bg-pink-500/10",
    authUrl: "https://www.facebook.com/v19.0/dialog/oauth",
    tokenUrl: "https://graph.facebook.com/v19.0/oauth/access_token",
    scopes: ["instagram_basic", "instagram_content_publish", "pages_show_list"],
    envClientId: "META_CLIENT_ID",
    envClientSecret: "META_CLIENT_SECRET",
  },
  FACEBOOK: {
    name: "Facebook",
    icon: "Facebook",
    color: "text-blue-500",
    bgColor: "bg-blue-500/10",
    authUrl: "https://www.facebook.com/v19.0/dialog/oauth",
    tokenUrl: "https://graph.facebook.com/v19.0/oauth/access_token",
    scopes: ["pages_show_list", "pages_read_engagement", "pages_manage_posts"],
    envClientId: "META_CLIENT_ID",
    envClientSecret: "META_CLIENT_SECRET",
  },
  LINKEDIN: {
    name: "LinkedIn",
    icon: "Linkedin",
    color: "text-blue-600",
    bgColor: "bg-blue-600/10",
    authUrl: "https://www.linkedin.com/oauth/v2/authorization",
    tokenUrl: "https://www.linkedin.com/oauth/v2/accessToken",
    scopes: ["openid", "profile", "w_member_social"],
    envClientId: "LINKEDIN_CLIENT_ID",
    envClientSecret: "LINKEDIN_CLIENT_SECRET",
  },
  TWITTER: {
    name: "X (Twitter)",
    icon: "Twitter",
    color: "text-foreground",
    bgColor: "bg-foreground/10",
    authUrl: "https://twitter.com/i/oauth2/authorize",
    tokenUrl: "https://api.twitter.com/2/oauth2/token",
    scopes: ["tweet.read", "tweet.write", "users.read"],
    envClientId: "TWITTER_CLIENT_ID",
    envClientSecret: "TWITTER_CLIENT_SECRET",
  },
  TIKTOK: {
    name: "TikTok",
    icon: "Music",
    color: "text-foreground",
    bgColor: "bg-foreground/10",
    authUrl: "https://www.tiktok.com/v2/auth/authorize/",
    tokenUrl: "https://open.tiktokapis.com/v2/oauth/token/",
    scopes: ["user.info.basic", "video.list"],
    envClientId: "TIKTOK_CLIENT_KEY",
    envClientSecret: "TIKTOK_CLIENT_SECRET",
  },
  THREADS: {
    name: "Threads",
    icon: "AtSign",
    color: "text-foreground",
    bgColor: "bg-foreground/10",
    authUrl: "https://threads.net/oauth/authorize",
    tokenUrl: "https://graph.threads.net/oauth/access_token",
    scopes: ["threads_basic", "threads_content_publish"],
    envClientId: "META_CLIENT_ID",
    envClientSecret: "META_CLIENT_SECRET",
  },
  YOUTUBE: {
    name: "YouTube",
    icon: "Youtube",
    color: "text-red-500",
    bgColor: "bg-red-500/10",
    authUrl: "https://accounts.google.com/o/oauth2/v2/auth",
    tokenUrl: "https://oauth2.googleapis.com/token",
    scopes: ["https://www.googleapis.com/auth/youtube.readonly"],
    envClientId: "GOOGLE_CLIENT_ID",
    envClientSecret: "GOOGLE_CLIENT_SECRET",
  },
  PINTEREST: {
    name: "Pinterest",
    icon: "MapPin",
    color: "text-red-600",
    bgColor: "bg-red-600/10",
    authUrl: "https://www.pinterest.com/oauth/",
    tokenUrl: "https://api.pinterest.com/v5/oauth/token",
    scopes: ["boards:read", "pins:read"],
    envClientId: "PINTEREST_APP_ID",
    envClientSecret: "PINTEREST_APP_SECRET",
  },
} as const

export type SocialOAuthPlatform = keyof typeof SOCIAL_OAUTH_CONFIG
